# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    pdf_dir: /var/www/faxit/www/pdf
    fax_choices:
      'Ron Wyden': '+12022282717'
      'Jeff Merkley': '+12022283997'
      'Earl Blumenauer': '+12022258941'

services:
    fax_storage:
        class:     AppBundle\Service\FaxService
        arguments:
            - '%pdf_dir%'
            - '%twilio_sid%'
            - '%twilio_token%'
            - '%twilio_phone_number%'
