# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value


services:
    fax_storage:
        class:     AppBundle\Service\FaxService
        arguments:
            - '%pdf_dir%'
            - '%twilio_sid%'
            - '%twilio_token%'
            - '%twilio_phone_number%'
