parameters:

services:
    storage_service:
        class:  AppBundle\Service\StorageService
        arguments:
            - '%pdf_dir%'

    fax_service:
        class:  AppBundle\Service\FaxService
        arguments:
            - '%twilio_sid%'
            - '%twilio_token%'
            - '%twilio_phone_number%'
            - '@storage_service'

    contact_repository:
        class: AppBundle\Repository\ContactRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Contact

    contact_service:
        class: AppBundle\Service\ContactService
        arguments:
            - '@contact_repository'
