# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    pdf_dir: /var/www/faxit/www/pdf

services:
    fax_storage:
        class:     AppBundle\Service\FaxService
        arguments:
            - '%pdf_dir%'
            - '%twilio_sid%'
            - '%twilio_token%'
            - '%twilio_phone_number%'
